### ISSUE TITLE
3dmigoto-blender Export Error

### ISSUE THREAD

**Issue by 53nemu** [DarkStarSword/3d-fixes#29]
Hi, I'm sorry to bother you again. 

When I use an older version plugin (created by you rather than modified by others), I encounter the following error when attempting to output the model
I aimed to delete the skirt from "polySurface6085_10" and remove the top while keeping the tie. So, I imported the 3DMigoto raw buffers (only importing "polySurface6085_10.ib" and "polySurface6085_10.vb"). 
Essentially, my objective is to unpack the original models within the game, make modifications, and repack them for the game to read.

However, afterwards, Blender prompts the following error:

Python: Traceback (most recent call last):
  File "C:\Users\ROG\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blender_3dmigoto (2).py", line 1399, in execute
    export_3dmigoto(self, context, vb_path, ib_path, fmt_path)
  File "C:\Users\ROG\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blender_3dmigoto (2).py", line 1044, in export_3dmigoto
    stride = obj['3DMigoto:VBStride']
KeyError: 'bpy_struct[key]: key "3DMigoto:VBStride" not found'

I have uploaded the older version of the plugin I used, and I would greatly appreciate it if you could take the time to help me identify where the issue might be occurring. Thank you very much for your assistance.

Also, my English is not very good, which might make it difficult for you to read. I'm really sorry.
[original model&old version plugin&modified model(blender file).zip](https://github.com/DarkStarSword/3d-fixes/files/13828478/original.model.old.version.plugin.modified.model.blender.file.zip)

**Comment by DarkStarSword** [comment]
Right, 3DMigoto stores a bunch of info in the custom properties attached to the object:
![image](https://github.com/DarkStarSword/3d-fixes/assets/379749/b20ede0d-ddcb-4d9a-baa1-250c2a84f4dd)

"3DMigoto:VBStride" became "3DMigoto:VB0Stride" in the update that added support for multiple vertex buffers - the new script can load .blend files with the old name for backwards compatibility, but the old script doesn't know about the new name hence that error. You should be able to rename the property in the custom properties panel if you need to.

**Comment by 53nemu** [comment]
> Right, the script stores a bunch of info in the custom properties attached to the object: ![image](https://private-user-images.githubusercontent.com/379749/294163426-b20ede0d-ddcb-4d9a-baa1-250c2a84f4dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNjc5MDYsIm5iZiI6MTcwNDM2NzYwNiwicGF0aCI6Ii8zNzk3NDkvMjk0MTYzNDI2LWIyMGVkZTBkLWRkY2ItNGQ5YS1iYWExLTI1MGMyYTg0ZjRkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxMTI2NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZGM2NGI3MjBhYzc1NjczMmM0M2M0MTkyOWRiNDEyYzliNjA3YjQzOWRjZWY3MjVjYTkyN2FhZGQyNTdlNmE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.S7MBG5BzxI3yrFTNnyirCnDYlP4w1qgpnBOwbLfkvjA)
> 
> "3DMigoto:VBStride" became "3DMigoto:VB0Stride" in the update that added support for multiple vertex buffers - the new script can load .blend files with the old name for backwards compatibility, but the old script doesn't know about the new name hence that error. You should be able to rename the property in the custom properties panel if you need to.

Thank you very much for your response. I have indeed tried the new version, but encountered some other issues. I would greatly appreciate it if you could help me with those as well.

I have downloaded the latest version you released.

When attempting to export the model, Blender defaults to using the .vb0 extension, resulting in four files with extensions .vb, .vb0, .fmt, and .vgmap. When I try to re-import a previously exported model (using the original .ib file with the .vb file having the .vb0 extension), Blender prompts me to provide the .fmt file. Regardless of whether I provide the original .fmt file from the unpacked data or the .fmt file generated during the export of the new model, I encounter the following error

Python: Traceback (most recent call last):
  File "C:\Users\ROG\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blender_3dmigoto.py", line 2561, in execute
    import_3dmigoto_raw_buffers(self, context, vb_fmt_path, ib_fmt_path, **migoto_raw_import_options)
  File "C:\Users\ROG\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blender_3dmigoto.py", line 2441, in import_3dmigoto_raw_buffers
    obj = import_3dmigoto(operator, context, paths, merge_meshes=False, **kwargs)
  File "C:\Users\ROG\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blender_3dmigoto.py", line 1305, in import_3dmigoto
    obj.append(import_3dmigoto_vb_ib(operator, context, [p], **kwargs))
  File "C:\Users\ROG\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blender_3dmigoto.py", line 1368, in import_3dmigoto_vb_ib
    (blend_indices, blend_weights, texcoords, vertex_layers, use_normals) = import_vertices(mesh, obj, vb, operator, semantic_translations, flip_normal)
  File "C:\Users\ROG\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blender_3dmigoto.py", line 1277, in import_vertices
    import_normals_step1(mesh, data, vertex_layers, operator, translate_normal)
  File "C:\Users\ROG\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blender_3dmigoto.py", line 1010, in import_normals_step1
    l.normal[:] = normals[l.vertex_index]
IndexError: list index out of range

When using the newly generated .vb file along with the original .ib file, it directly triggers an error. This issue might arise due to compatibility problems between the newly exported .vb file and the original .ib file. 

Could you please confirm?
![first](https://github.com/DarkStarSword/3d-fixes/assets/153263868/b56fdce7-dc93-4016-a49f-ce32eb79c262)
![second](https://github.com/DarkStarSword/3d-fixes/assets/153263868/e2a5b2c8-60b0-46e6-b353-97da7c39ef8f)
[polySurface6085_10.zip](https://github.com/DarkStarSword/3d-fixes/files/13829452/polySurface6085_10.zip)

in zip there are the original .ib file and export file by the lastest plugin (the .vb0 file has been renamed)

**Comment by 53nemu** [comment]
> Right, the script stores a bunch of info in the custom properties attached to the object: ![image](https://private-user-images.githubusercontent.com/379749/294163426-b20ede0d-ddcb-4d9a-baa1-250c2a84f4dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNzAxNzUsIm5iZiI6MTcwNDM2OTg3NSwicGF0aCI6Ii8zNzk3NDkvMjk0MTYzNDI2LWIyMGVkZTBkLWRkY2ItNGQ5YS1iYWExLTI1MGMyYTg0ZjRkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxMjA0MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjc1NTkxZTk0YTNmYWZlMmU5MjZmMDg2OWZhYTJlY2U1OWIwMDFiN2Y3NmMwMjBjMTA3OTUxZjRiMzQ3NDc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U2NsBiPz2DcbGMpGvYNDNsCuTZaIqNFw_t3w0ag1ZRk)
> 
> "3DMigoto:VBStride" became "3DMigoto:VB0Stride" in the update that added support for multiple vertex buffers - the new script can load .blend files with the old name for backwards compatibility, but the old script doesn't know about the new name hence that error. You should be able to rename the property in the custom properties panel if you need to.

Oh, my goodness! I was able to export and re-import successfully after changing 3DMigoto:VBStride in the settings. Thank you! This is my first time creating a mod for the legend of heroes: hajimari no kiseki, and also my first time modifying 3D mods. I'm so grateful for your help.
