### ISSUE TITLE
Trianglestrip support

### ISSUE THREAD

**Issue by DanCraid** [DarkStarSword/3d-fixes#38]
is Trianglestrip supported?? a game uses that and fails to import in blender using latest plugin

Python: Traceback (most recent call last):
  File "\blender_3dmigoto.py", line 2340, in execute
  File "\blender_3dmigoto.py", line 1314, in import_3dmigoto
  File "\blender_3dmigoto.py", line 1332, in import_3dmigoto_vb_ib
  File "\blender_3dmigoto.py", line 935, in load_3dmigoto_mesh
  File "\blender_3dmigoto.py", line 576, in __init__
  File "\blender_3dmigoto.py", line 584, in parse_vb_txt
  File "\blender_3dmigoto.py", line 462, in __init__
  File "\blender_3dmigoto.py", line 492, in parse_vb_txt
AssertionError

These are the files im trying to import:

[000027-ib=ddf08b10-vs=2c8924c60e725b3f-ps=e1eb31d7d907b2f5.txt](https://github.com/user-attachments/files/17173923/000027-ib.ddf08b10-vs.2c8924c60e725b3f-ps.e1eb31d7d907b2f5.txt)
[000027-vb0=e5f4a3e6-vs=2c8924c60e725b3f-ps=e1eb31d7d907b2f5.txt](https://github.com/user-attachments/files/17173924/000027-vb0.e5f4a3e6-vs.2c8924c60e725b3f-ps.e1eb31d7d907b2f5.txt)

**Comment by SheLikesCloth** [comment]
Tales of Berseria is one such game
